# Generated by Django 5.1.2 on 2024-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
