# Generated by Django 5.1.2 on 2024-10-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
