# Generated by Django 5.1.2 on 2024-10-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('descriptoin', models.CharField(max_length=255)),
                ('work_time', models.IntegerField()),
                ('social_network', models.CharField(max_length=255)),
            ],
        ),
    ]
